Nahyara
NExT-2023-1/t03-comparacao-de-imagens pull request #7
Opened 2023-09-17 01:45 UTC by nahyarabs

2023-09-17 02:29 UTC, txaves requested changes

2023-09-17 02:29 UTC, txaves commented on src/main/java/next/finalproject/t03/imagecomparison/controller/ImageController.java
> +	@PostMapping("/compareAll")
Mudar a URL para algo mais próximo do que realmente é feito pois com esse nome parece que todas as imagens serão comparadas entre si

2023-09-19 00:06 UTC, nahyarabs commented on src/main/java/next/finalproject/t03/imagecomparison/controller/ImageController.java
> +	@PostMapping("/compareAll")
corrigido

2023-09-19 11:54 UTC, txaves approved these changes

2023-09-19 11:54 UTC, merged